export const Users = [
    {
      id: 1,
      name: "Sunny Lehal",
      username: "sunny_22",
      email: "SunnyLehal@hotmail.com",
      Picture: "/assets/face1.jpg",
    },
    {
      id: 2,
      name: "Harmeet Hans",
      username: "Harmeet_hans",
      email: "Harmeet@gmail.com",
      Picture: "/assets/face2.jpg",
    },
    {
      id: 3,
      name: "Japnam Gill",
      username: "Japnam_gill",
      email: "Japnamgill@homtail.com",
      Picture: "/assets/face3.jpg",
    },
    {
      id: 4,
      name: "Karamvir Sekhon",
      username: "Karamvir_sekhon",
      email: "Karamvirsekhon@gmail.com",
      Picture: "/assets/face4.jpg",
    },
    {
      id: 5,
      name: "Navdeep Gill",
      username: "navdeep_gill",
      email: "Navdeepgill@hotmail.com",
      Picture: "/assets/face5.jpg",
    },
  ];
  
  export const Posts = [
    {
      userId: 3,
      id: 1,
      title: "ONE PIECE",
      body: "ONE PIECE!!!!",
      photo: "/assets/random4.jpg",
      date: "10 mins ago",
      like: "20",
      comment: "20",
    },
    {
      userId: 2,
      id: 2,
      title: "i love soccer",
      body: "pizza hut is the best pizza ever",
      photo: "/assets/random9.jpg",
      date: "24 mins ago",
      like: "254",
      comment: "214",
    },
    {
      userId: 1,
      id: 3,
      title: "i love soccer",
      body: "cutest dog ever!!",
      photo: "/assets/random3.jpg",
      date: "15 hours ago",
      like: "10",
      comment: "26",
    },
  
    {
      userId: 3,
      id: 4,
      title: "Best soccer player in the world next to messi",
      body: "Best soccer player in the world next to messi",
      photo: "/assets/random7.jpg",
      date: "24 hours ago",
      like: "25",
      comment: "36",
    },
    {
      userId: 4,
      id: 5,
      title: "i love soccer",
      body: "tilt proof",
      photo: "/assets/random6.jpg",
      date: "3 days ago",
      like: "458",
      comment: "150",
    },
    {
      userId: 2,
      id: 6,
      title: "i love soccer",
      body: "still don't know my lefts and rights :( ",
      photo: "/assets/random2.jpg",
      date: "4 days ago",
      like: "123",
      comment: "36",
    },
    {
      userId: 1,
      id: 7,
      title: "i love soccer",
      body: "THE GOAT",
      photo: "/assets/random10.jpg",
      date: "1 weeks ago",
      like: "11",
      comment: "35",
    },
    {
      userId: 4,
      id: 8,
      title: "i love soccer",
      body: "DEKU!",
      photo: "/assets/random11.jpg",
      date: "2 weeks ago",
      like: "789",
      comment: "456",
    },
    // {
    //   userId: 1,
    //   id: 9,
    //   title: "i love soccer",
    //   body: "i love soccer",
    //   photo: "/assets/face1.jpg",
    //   date: "1 months ago",
    //   like: "100",
    //   comment: "31",
    // },
    // {
    //   userId: 2,
    //   id: 10,
    //   title: "i love soccer",
    //   body: "i love soccer",
    //   photo: "/assets/face1.jpg",
    //   date: "2 months ago",
    //   like: "85",
    //   comment: "15",
    // },
    // {
    //   userId: 3,
    //   id: 11,
    //   title: "i love soccer",
    //   body: "i love soccer",
    //   photo: "/assets/face1.jpg",
    //   date: " 8 months ago",
    //   like: "152",
    //   comment: "545",
    // },
    // {
    //   userId: 1,
    //   id: 12,
    //   title: "i love soccer",
    //   body: "i love soccer",
    //   photo: "/assets/face1.jpg",
    //   date: "9 months ago",
    //   like: "520",
    //   comment: "456",
    // },
    // {
    //   userId: 2,
    //   id: 13,
    //   title: "i love soccer",
    //   body: "i love soccer",
    //   photo: "/assets/face1.jpg",
    //   date: "11 hours ago",
    //   like: "15",
    //   comment: "32",
    // },
    // {
    //   userId: 4,
    //   id: 14,
    //   title: "i love soccer",
    //   body: "i love soccer",
    //   photo: "/assets/face1.jpg",
    //   date: "2 year ago",
    //   like: "52",
    //   comment: "6",
    // },
  ];